[package]
name = "movefile"
version = "0.1.0"
edition = "2021"
readme = "README.md"
categories = ["util"]
license = "MIT"
repository = "https://github.com/mrdkprj/movefile"

[package.metadata.docs.rs]
targets = [
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu"
]

[lib]
name = "movefile"
path = "src/lib.rs"

[dependencies]
once_cell = "1.19.0"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58"
features = [
  "Foundation",
  "Win32_Storage_FileSystem",
  "Win32_Security",
  "Win32_System_Com",
  "Win32_UI_Shell",
  "Win32_System_WindowsProgramming"
]

[target.'cfg(target_os = "linux")'.dependencies.gio]
version = "0.18.4"

[profile.release]
opt-level = "s"
debug = false
strip = "none"
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false
